import { test, expect } from '@playwright/test';

test('admin manages products; customer places an unpaid order and downloads a real PDF', async ({ page, browser }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/admin');
  await page.getByLabel('Email', { exact: true }).fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('test-admin-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Products', exact: true }).click();
  await page.getByRole('button', { name: '+ Add product', exact: true }).click();
  await page.getByLabel('Product title').fill('Studio Headphones');
  await page.getByLabel('SKU', { exact: true }).fill('STUDIO-001');
  await page.getByLabel('Category', { exact: true }).fill('Audio');
  await page.getByLabel('Price (USD)').fill('129.99');
  await page.getByLabel('Available stock').fill('4');
  await page.getByLabel('Description', { exact: true }).fill('Comfortable wired headphones with replaceable cushions.');
  await page.getByRole('button', { name: 'Save product', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'STUDIO-001' })).toBeVisible();
  const context = await browser.newContext(); const buyer = await context.newPage();
  buyer.on('pageerror', e => errors.push(e.message));
  await buyer.goto('/?view=account');
  await buyer.getByRole('button', { name: 'New here? Create an account' }).click();
  await buyer.getByLabel('Full name').fill('Browser Customer');
  await buyer.getByLabel('Email', { exact: true }).fill('buyer@example.test');
  await buyer.getByLabel('Password', { exact: true }).fill('test-buyer-password');
  await buyer.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(buyer.getByRole('heading', { name: 'Browser Customer' })).toBeVisible();
  await buyer.getByRole('button', { name: 'Shop', exact: true }).click();
  await buyer.getByRole('button', { name: 'Add Studio Headphones to cart', exact: true }).click();
  await expect(buyer.getByRole('status')).toContainText('Added to your cart');
  await buyer.getByRole('button', { name: 'Cart', exact: true }).click();
  await buyer.getByLabel('Recipient name').fill('Browser Customer');
  await buyer.getByLabel('Street address', { exact: true }).fill('123 Main Street');
  await buyer.getByLabel('City', { exact: true }).fill('New York');
  await buyer.getByLabel('State / region').fill('NY');
  await buyer.getByLabel('Postal code').fill('10001');
  await buyer.getByRole('button', { name: 'Create order & review total' }).click();
  await expect(buyer.getByRole('heading', { name: 'Your orders', exact: true })).toBeVisible();
  await expect(buyer.locator('.status').first()).toHaveText('pending payment');
  await expect(buyer.getByRole('button', { name: 'Pay securely' })).toBeDisabled();
  const receiptUrl = await buyer.getByRole('link', { name: 'Download receipt' }).getAttribute('href');
  const receipt = await context.request.get(receiptUrl!);
  expect(receipt.status()).toBe(200); expect((await receipt.body()).subarray(0, 5).toString()).toBe('%PDF-');
  await buyer.reload(); await expect(buyer.getByText('Studio Headphones × 1')).toBeVisible();
  await buyer.goto('/admin'); await expect(buyer.getByRole('heading', { name: 'Administrator access required' })).toBeVisible();
  await buyer.goto('/'); await buyer.setViewportSize({ width: 390, height: 844 });
  expect(await buyer.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await buyer.screenshot({ path: 'test-results/storefront-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.screenshot({ path: 'test-results/admin-dashboard.png', fullPage: true });
  expect(errors).toEqual([]); await context.close();
});
