module.exports = {content: ["./index.html", "./src/**/*.{ts,tsx}"], ...{
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-container-low": "#f2f3ff",
              "surface-container-lowest": "#ffffff",
              "on-primary-container": "#eeefff",
              "secondary-fixed": "#ffdbd1",
              "primary-container": "#2563eb",
              "on-surface-variant": "#434655",
              "surface-tint": "#0053db",
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#6ffbbe",
              "on-error": "#ffffff",
              "inverse-surface": "#283044",
              "error": "#ba1a1a",
              "on-background": "#131b2e",
              "on-tertiary-container": "#bdffdb",
              "outline-variant": "#c3c6d7",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "surface-variant": "#dae2fd",
              "primary": "#004ac6",
              "secondary-container": "#fe5824",
              "tertiary": "#006242",
              "on-tertiary-fixed-variant": "#005236",
              "secondary": "#b02f00",
              "tertiary-fixed-dim": "#4edea3",
              "secondary-fixed-dim": "#ffb5a0",
              "primary-fixed": "#dbe1ff",
              "primary-fixed-dim": "#b4c5ff",
              "inverse-primary": "#b4c5ff",
              "surface-bright": "#faf8ff",
              "outline": "#737686",
              "on-secondary": "#ffffff",
              "on-primary-fixed-variant": "#003ea8",
              "background": "#faf8ff",
              "surface-dim": "#d2d9f4",
              "on-primary-fixed": "#00174b",
              "surface-container": "#eaedff",
              "on-secondary-container": "#531100",
              "on-surface": "#131b2e",
              "surface-container-high": "#e2e7ff",
              "on-error-container": "#93000a",
              "on-secondary-fixed": "#3b0900",
              "surface": "#faf8ff",
              "inverse-on-surface": "#eef0ff",
              "on-secondary-fixed-variant": "#862200",
              "tertiary-container": "#007d55",
              "surface-container-highest": "#dae2fd",
              "on-tertiary-fixed": "#002113"
            },
            borderRadius: {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "2xl": "1rem",
              "3xl": "1.5rem",
              "full": "9999px"
            },
            spacing: {
              "space-xs": "0.25rem",
              "gutter": "1rem",
              "space-lg": "1.5rem",
              "space-sm": "0.5rem",
              "space-xl": "2rem",
              "space-md": "1rem",
              "margin": "1rem"
            },
            fontFamily: {
              "headline-md": ["Plus Jakarta Sans", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "label-md": ["Plus Jakarta Sans", "sans-serif"],
              "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "label-lg": ["Plus Jakarta Sans", "sans-serif"],
              "label-sm": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
              "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg": ["Plus Jakarta Sans", "sans-serif"]
            }
          }
        }
      }};
