import React, { useCallback, useEffect, useState } from 'react';
import type { Session, Settings, Capabilities } from './types';
import { request } from './api';
import { AuthForm, Banner, StoreContext } from './shared';
import { Catalog, Cart, Orders, SavingsPage, Account, Tickets } from './Storefront';
import { Dashboard, ProductsAdmin, OrdersAdmin, CustomersAdmin, PromotionsAdmin, SavingsAdmin, SettingsAdmin, AuditAdmin } from './Admin';
import './product.css';

export default function ProductApp() {
  const admin = location.pathname.startsWith('/admin');
  const [page, setPage] = useState(new URLSearchParams(location.search).get('view') || (admin ? 'dashboard' : 'shop'));
  const [session, setSession] = useState<Session | null>(null), [config, setConfig] = useState<Settings | null>(null), [capabilities, setCapabilities] = useState<Capabilities | null>(null), [error, setError] = useState(''), [version, setVersion] = useState(0), [toast, setToast] = useState('');
  const refresh = useCallback(async () => { const [session, config, capabilities] = await Promise.all([request<Session>('/auth/session'), request<Settings>('/store'), request<Capabilities>('/capabilities')]); setSession(session); setConfig(config); setCapabilities(capabilities); setVersion(v => v + 1); setError(''); }, []);
  useEffect(() => { void refresh().catch(e => setError(e.message)); }, [refresh]);
  useEffect(() => { const handler = () => setPage(new URLSearchParams(location.search).get('view') || (admin ? 'dashboard' : 'shop')); window.addEventListener('popstate', handler); return () => window.removeEventListener('popstate', handler); }, [admin]);
  useEffect(() => { if (config) document.title = `${admin ? 'Admin · ' : ''}${config.name}`; }, [config, admin]);
  useEffect(() => { if (!toast) return; const timeout = window.setTimeout(() => setToast(''), 5000); return () => clearTimeout(timeout); }, [toast]);
  const navigate = (value: string) => { setPage(value); history.pushState({}, '', `${admin ? '/admin' : '/'}?view=${value}`); window.scrollTo(0, 0); };
  if (!session || !config || !capabilities) return <main className="product-app boot-screen"><h1>VoltMart</h1>{error ? <><Banner error={error} /><button onClick={() => void refresh().catch(e => setError(e.message))}>Retry connection</button></> : <p role="status">Loading your store…</p>}</main>;
  const adminPages = [['dashboard', 'Overview', '◫'], ['products', 'Products', '▦'], ['orders', 'Orders', '▤'], ['customers', 'Customers', '♙'], ['vouchers', 'Vouchers', '◇'], ['savings', 'Savings plans', '◉'], ['support', 'Support inbox', '☏'], ['settings', 'Settings', '⚙'], ['audit', 'Audit history', '≡']];
  const storePages = [['shop', 'Shop'], ['cart', 'Cart'], ['orders', 'Orders'], ['savings', 'Savings'], ['support', 'Support'], ['account', session.user ? 'Account' : 'Sign in']];
  let content: React.ReactNode;
  if (admin && !session.user) content = <AuthForm />;
  else if (admin && session.user?.role !== 'admin') content = <section className="panel"><h1>Administrator access required</h1><p>Your customer account cannot access store administration.</p><a href="/">Return to store</a></section>;
  else if (admin) content = page === 'products' ? <ProductsAdmin /> : page === 'orders' ? <OrdersAdmin /> : page === 'customers' ? <CustomersAdmin /> : page === 'vouchers' ? <PromotionsAdmin /> : page === 'savings' ? <SavingsAdmin /> : page === 'support' ? <Tickets admin /> : page === 'settings' ? <SettingsAdmin /> : page === 'audit' ? <AuditAdmin /> : <Dashboard navigate={navigate} />;
  else if (!session.user && page !== 'shop') content = <AuthForm />;
  else content = page === 'cart' ? <Cart navigate={navigate} /> : page === 'orders' ? <Orders /> : page === 'savings' ? <SavingsPage /> : page === 'account' ? <Account /> : page === 'support' ? <Tickets /> : <Catalog navigate={navigate} />;
  return <StoreContext.Provider value={{ user: session.user, config, capabilities, refresh, version, notify: setToast }}><div className={`product-app ${admin ? 'admin-app' : 'shop-app'}`}><a className="skip-link" href="#main-content">Skip to content</a>{admin ? <><aside className="admin-sidebar"><a className="brand" href="/admin"><span className="brand-symbol">V</span>{config.name}<small>ADMIN</small></a><p className="nav-caption">WORKSPACE</p><nav aria-label="Administration">{adminPages.map(([key, label, icon]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => navigate(key)}><span aria-hidden>{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><a href="/">Visit storefront ↗</a><a href="/documentation/">Documentation ↗</a></div></aside><header className="admin-topbar"><span>Store management</span><div><span className="avatar">{session.user?.name.charAt(0) || 'V'}</span>{session.user?.name || 'Administrator'}{session.user && <button onClick={() => void request('/auth/logout', 'POST').then(refresh).catch(e => setError(e.message))}>Sign out</button>}</div></header></> : <><div className="store-announcement">{config.name} · Shop in {config.currency} · Delivery within {config.country}</div><header className="store-header"><a href="/" className="brand"><span className="brand-symbol">V</span>{config.name}</a><nav aria-label="Store">{storePages.map(([key, label]) => <button key={key} onClick={() => navigate(key)} className={page === key ? 'active' : ''}>{label}</button>)}</nav>{session.user?.role === 'admin' && <a className="admin-link" href="/admin">Admin ↗</a>}</header></>}<main id="main-content" className={admin ? 'admin-main' : 'store-main'}><Banner error={error} />{content}</main>{!admin && <footer className="store-footer"><strong>{config.name}</strong><p>{config.address}</p><div><a href="/documentation/">Documentation</a>{config.supportEmail && <a href={`mailto:${config.supportEmail}`}>Contact the store</a>}</div><small>Prices shown in {config.currency}. Payment and shipping availability depend on store configuration.</small></footer>}{toast && <div role="status" className="toast">✓ {toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}>×</button></div>}</div></StoreContext.Provider>;
}
